<?php

namespace ClubBundle\Repository;

/**
 * PupilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PupilRepository extends \Doctrine\ORM\EntityRepository
{
}
