<?php

namespace ExamsBundle\Repository;

/**
 * classesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classesRepository extends \Doctrine\ORM\EntityRepository
{
}
