<?php

namespace ExamsBundle\Repository;

/**
 * examRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class examRepository extends \Doctrine\ORM\EntityRepository
{
}
