<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYtwcmxw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYtwcmxw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYtwcmxw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYtwcmxw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYtwcmxw\appDevDebugProjectContainer([
    'container.build_hash' => 'Ytwcmxw',
    'container.build_id' => 'ebccaa09',
    'container.build_time' => 1582733752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYtwcmxw');
