<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4jxhdoh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4jxhdoh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4jxhdoh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4jxhdoh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4jxhdoh\appDevDebugProjectContainer([
    'container.build_hash' => '4jxhdoh',
    'container.build_id' => '0f313689',
    'container.build_time' => 1592560821,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4jxhdoh');
