<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3f0kgx9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3f0kgx9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3f0kgx9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3f0kgx9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3f0kgx9\appDevDebugProjectContainer([
    'container.build_hash' => '3f0kgx9',
    'container.build_id' => 'cf5d83cd',
    'container.build_time' => 1592613215,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3f0kgx9');
