homeback:
    path: /homeback
    defaults: {_controller: ExamsBundle:Default:backindex }
exams_homepage:
    path:     /homef
    defaults: { _controller: ExamsBundle:Default:index }
afficheexams:
    path:     /listeexams
    defaults: {_controller: ExamsBundle:Exam:reader}
affichebackexams:
    path:     /listbackexams
    defaults: {_controller: ExamsBundle:Exam:read}
affichegrades:
    path:     /listegrades
    defaults: {_controller: ExamsBundle:Grade:reader}
affichebackgrades:
    path:     /listbackgrades
    defaults: {_controller: ExamsBundle:Grade:read}
createexams:
    path:     /admin/createexams
    defaults: {_controller: ExamsBundle:Exam:create}
creategrades:
    path:     /teacher/creategrades
    defaults: {_controller: ExamsBundle:Grade:create}
updateexams:
    path:     /admin/updatee/{id}
    defaults: {_controller: ExamsBundle:Exam:update}
updategrades:
    path:     /teacher/updateg/{id}
    defaults: {_controller: ExamsBundle:Grade:update}
deleteexams:
    path:     /admin/deletee/{id}
    defaults: {_controller: ExamsBundle:Exam:delete}
deletegrades:
    path:     /teacher/deleteg/{id}
    defaults: {_controller: ExamsBundle:Grade:delete}