<?php

namespace Proxies\__CG__\ExamsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class grade extends \ExamsBundle\Entity\grade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'idG', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'subject', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'teacher', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'pupil', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'grade', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'idExam'];
        }

        return ['__isInitialized__', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'idG', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'subject', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'teacher', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'pupil', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'grade', '' . "\0" . 'ExamsBundle\\Entity\\grade' . "\0" . 'idExam'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (grade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdExam($idExam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdExam', [$idExam]);

        return parent::setIdExam($idExam);
    }

    /**
     * {@inheritDoc}
     */
    public function getidExam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidExam', []);

        return parent::getidExam();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdG()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdG();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdG', []);

        return parent::getIdG();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeacher($teacher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeacher', [$teacher]);

        return parent::setTeacher($teacher);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacher', []);

        return parent::getTeacher();
    }

    /**
     * {@inheritDoc}
     */
    public function setPupil($pupil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPupil', [$pupil]);

        return parent::setPupil($pupil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPupil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPupil', []);

        return parent::getPupil();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade($grade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', [$grade]);

        return parent::setGrade($grade);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', []);

        return parent::getGrade();
    }

}
